'use client';
import {useState,useEffect,useRef} from 'react';
import {ChevronDown,Menu,X} from 'lucide-react';
const groups:Record<string,{title?:string;links:[string,string][]}[]>={Product:[{title:'Platform',links:[['PUKU Cloud','/cloud'],['PUKU Desktop','/desktop'],['PUKU CLI','/cli']]},{title:'Features',links:[['PUKU Review','/review'],['PUKU Windows VM','/windows']]}],Solutions:[{links:[['Government','/government'],['Partners','/solutions/partners'],['AI Productivity Guarantee','/guarantee'],['Security','/security']]}],Resources:[{links:[['Docs','/docs'],['Community','/community'],['PUKU University','/university'],['Blog','/blog'],['Careers','/careers']]}]};
const href=(url:string)=>url;
export default function Header(){const[open,setOpen]=useState<string|null>(null);const[mobile,setMobile]=useState(false);const ref=useRef<HTMLElement>(null);
useEffect(()=>{function outside(e:PointerEvent){if(!ref.current?.contains(e.target as Node))setOpen(null)}function key(e:KeyboardEvent){if(e.key==='Escape'){setOpen(null);setMobile(false)}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key)}},[]);
useEffect(()=>{document.body.style.overflow=mobile?'hidden':'';const surfaces=document.querySelectorAll<HTMLElement>('main,footer');surfaces.forEach(el=>{el.inert=mobile});return()=>{document.body.style.overflow='';surfaces.forEach(el=>{el.inert=false})}},[mobile]);
const navigation=()=>['Product','Solutions','Customers','Resources','Pricing'].map(name=>groups[name]?<div className="nav-group" key={name}><button className={'nav-trigger '+(open===name?'active':'')} aria-expanded={open===name} aria-controls={'menu-'+name} onClick={()=>setOpen(open===name?null:name)}>{name}<ChevronDown size={14} strokeWidth={1.8} className={open===name?'rotate-180':''}/></button>{open===name&&<div id={'menu-'+name} className={'nav-dropdown '+(name==='Product'?'product-dropdown':'')}>{groups[name].map((group,i)=><div className="menu-column" key={i}>{group.title&&<span className="menu-label">{group.title}</span>}{group.links.map(([label,url])=><a href={href(url)} key={label}>{label}</a>)}</div>)}</div>}</div>:<a className="nav-link" key={name} href={href('/'+name.toLowerCase())}>{name}</a>);
const actions=()=> <><a className="demo-link" href="/demo">Get a Demo</a><a className="header-button outline" href="/download">Download</a><a className="header-button solid" href="/login">Log in</a></>;
return <header className="site-header" ref={ref}><a className="skip-link" href="#main-content">Skip to content</a><a href="/" aria-label="PUKU home" className="brand-logo"><img src="/puku-logo.png" alt="PUKU" width="24" height="30"/></a><nav className="desktop-nav" aria-label="Main navigation">{navigation()}</nav><div className="desktop-actions">{actions()}</div><button className="mobile-toggle" aria-label="Toggle menu" aria-expanded={mobile} onClick={()=>{setMobile(!mobile);setOpen(null)}}>{mobile?<X size={23} strokeWidth={1.5}/>:<Menu size={23} strokeWidth={1.5}/>}</button>{mobile&&<div className="mobile-drawer" role="dialog" aria-modal="true" aria-label="Site menu"><nav aria-label="Mobile navigation">{navigation()}</nav><div className="mobile-actions">{actions()}</div></div>}</header>}
