'use client';
import {useEffect,useRef,useState} from 'react';
import {X,Check,ArrowRight} from 'lucide-react';
export default function PageInteractions({children,slug}:{children:React.ReactNode;slug:string}){const ref=useRef<HTMLDivElement>(null);const[notice,setNotice]=useState('');const[modal,setModal]=useState('');
useEffect(()=>{const root=ref.current;if(!root)return;let timer:ReturnType<typeof setTimeout>;const announce=(s:string)=>{setNotice(s);clearTimeout(timer);timer=setTimeout(()=>setNotice(''),4000)};
const restorePrivacy=()=>{let saved:string|null=null;try{saved=localStorage.getItem('puku-privacy-opt-out')}catch{}if(saved===null)return;root.querySelectorAll<HTMLElement>('[role=switch]').forEach(button=>{const checked=saved==='true';button.setAttribute('aria-checked',String(checked));button.style.background=checked?'#3210ff':'#d2d2d2';const knob=button.firstElementChild as HTMLElement;if(knob)knob.style.transform=checked?'translateX(20px)':'translateX(0)';button.parentElement?.parentElement?.querySelectorAll('p').forEach(p=>{if(p.textContent?.startsWith('Status:'))p.textContent='Status: '+(checked?'Opted out':'Not opted out')})})};if(slug==='privacy-choices')restorePrivacy();
const copy=async(s:string)=>{try{await navigator.clipboard.writeText(s);announce('Copied to clipboard')}catch{setModal(s)}};
const submit=(event:Event)=>{const form=event.target as HTMLFormElement;if(!form.matches('form'))return;event.preventDefault();if(!form.reportValidity())return;if(slug==='review'){setModal('Connect your repository to run PUKU Review. The code review below is an interactive sample.');return;}setModal('Thank you. Your request is ready. This preview does not send information; connect your PUKU account or contact service to receive submissions.');};
const click=(event:MouseEvent)=>{const target=event.target as HTMLElement;const button=target.closest<HTMLButtonElement>('button,[role="switch"]');if(!button||!root.contains(button))return;const label=(button.getAttribute('aria-label')||button.textContent||'').trim();
if(button.getAttribute('type')==='submit'||button.closest('form'))return;
if(button.getAttribute('role')==='switch'){const checked=button.getAttribute('aria-checked')!=='true';button.setAttribute('aria-checked',String(checked));button.style.background=checked?'#3210ff':'#d2d2d2';const knob=button.firstElementChild as HTMLElement;if(knob)knob.style.transform=checked?'translateX(20px)':'translateX(0)';try{localStorage.setItem('puku-privacy-opt-out',String(checked))}catch{};const box=button.parentElement?.parentElement;box?.querySelectorAll('p').forEach(p=>{if(p.textContent?.startsWith('Status:'))p.textContent='Status: '+(checked?'Opted out':'Not opted out')});announce('Privacy preference saved');return;}
if(slug==='customers'&&['Testing & QA Automation','Greenfield Development','Code Maintenance'].includes(label)){button.setAttribute('aria-pressed',String(button.getAttribute('aria-pressed')!=='true'));button.classList.toggle('filter-checked',button.getAttribute('aria-pressed')==='true');applyFilters();return;}
if(button.hasAttribute('data-installer')){setModal('The PUKU CLI installer has not been published on this preview.');return;}
const controls=button.getAttribute('aria-controls');if(controls){const panel=document.getElementById(controls);if(panel){const expanded=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(expanded));panel.setAttribute('aria-hidden',String(!expanded));panel.style.gridTemplateRows=expanded?'1fr':'0fr';panel.style.display=expanded?'grid':'';panel.querySelectorAll<HTMLElement>('[hidden]').forEach(x=>x.hidden=!expanded);const icon=button.querySelector('svg');if(icon)icon.style.transform=expanded?'rotate(45deg)':'';return;}}
if(/curl|Copy|copy/.test(label)){copy(label.includes('curl')?'# PUKU CLI installation\n# Add your published PUKU installer URL here.':button.closest('pre,article,section')?.textContent?.slice(0,3000)||label);return;}
if(/Log in|Login/.test(label)){location.href='/login';return;}if(/Sign up/.test(label)){location.href='/signup';return;}
if(/Mark.*(read|viewed|resolved)/i.test(label)){button.setAttribute('aria-pressed',String(button.getAttribute('aria-pressed')!=='true'));button.style.opacity='.5';announce('Marked as '+(/resolved/.test(label)?'resolved':'reviewed'));return;}
if(/^(PUKU Cloud|PUKU Desktop|PUKU CLI)$/.test(label)){const group=button.parentElement;group?.querySelectorAll('button').forEach(b=>{b.setAttribute('aria-selected',String(b===button));b.style.borderColor=b===button?'#3210ff':'#ddd';b.style.color=b===button?'#191919':'#777'});const section=group?.parentElement;section?.querySelectorAll<HTMLImageElement>('img[alt^="PUKU"]').forEach(img=>{img.style.visibility=img.alt===label?'visible':'hidden';});const desc=section?.querySelector('p:last-child');if(desc)desc.textContent=label==='PUKU Cloud'?'Parallel agents in secure cloud VMs. Close your laptop, come back to finished PRs.':label==='PUKU Desktop'?'Manage fleets of local and cloud agents from one surface.':'The AI software engineer in your terminal, with every frontier model.';return;}
if(/^(Previous|Next|Show slide \d)/.test(label)){const section=button.closest('section')||button.parentElement?.parentElement?.parentElement;if(section){const track=section.querySelector<HTMLElement>('[class*="overflow-x"],[class*="overflow-hidden"]');if(track){track.scrollBy({left:(label==='Previous'?-1:1)*track.clientWidth*.75,behavior:'smooth'});const inner=track.firstElementChild as HTMLElement;if(inner&&track.scrollWidth<=track.clientWidth){const index=Number(track.dataset.slide||0)+(label==='Previous'?-1:1);track.dataset.slide=String(Math.max(0,index));inner.style.transform=`translateX(-${Math.max(0,index)*35}%)`;}}section.querySelectorAll('button').forEach(b=>b.disabled=false);}return;}
if(/More use cases/.test(label)){const options=button.nextElementSibling as HTMLElement;if(options){const expanded=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(expanded));options.style.visibility=expanded?'visible':'hidden';options.style.opacity=expanded?'1':'0';options.style.transform=expanded?'translateY(0)':'';}return;}
if(/Play|Watch|demo/i.test(label)){setModal('video');return;}
if(label==='Dismiss'){button.parentElement?.remove();return;}
if(/Submit PR|sgl-project|openai\/codex|microsoft\/vscode/.test(label)){setModal('PUKU Review preview. Connect your repository to review pull requests.');return;}
if(/SWE-|Claude|Codex|OpenCode|Cascade|PUKU Local/.test(label)){announce(`${label} selected`);button.setAttribute('aria-pressed','true');return;}
if(/Expand|Collapse|Read explanation/.test(label)){const parent=button.parentElement;button.setAttribute('aria-expanded',String(button.getAttribute('aria-expanded')!=='true'));if(parent){parent.classList.toggle('puku-expanded');announce(button.getAttribute('aria-expanded')==='true'?'Details expanded':'Details collapsed')}return;}
};
const applyFilters=()=>{const selected=[...root.querySelectorAll<HTMLInputElement>('input[type=checkbox]:checked')].map(i=>(i.closest('label')?.textContent||'').trim()).concat([...root.querySelectorAll<HTMLButtonElement>('button[aria-pressed=true]')].map(b=>(b.textContent||'').trim()));root.querySelectorAll<HTMLAnchorElement>('a[data-usecases]').forEach(a=>{const categories=(a.dataset.usecases||'').split('|');a.hidden=selected.length>0&&!selected.some(t=>categories.includes(t));});root.querySelectorAll<HTMLInputElement>('input[type=checkbox]').forEach(i=>i.closest('label')?.classList.toggle('filter-checked',i.checked));let empty=root.querySelector<HTMLElement>('[data-filter-empty]');if(!empty){empty=document.createElement('p');empty.dataset.filterEmpty='true';empty.className='puku-filter-empty';empty.textContent='No stories match these filters. Clear a filter to see more.';root.querySelector('a[data-usecases]')?.parentElement?.append(empty)}if(empty)empty.hidden=[...root.querySelectorAll<HTMLAnchorElement>('a[data-usecases]')].some(a=>!a.hidden);};const change=(event:Event)=>{const el=event.target as HTMLInputElement;if(slug==='customers'&&el.type==='checkbox')applyFilters();};
const picker=root.querySelector<HTMLElement>('[aria-label^="Interactive demo"]');const rows=picker?[...picker.querySelectorAll<HTMLElement>(':scope > .flex.flex-col > .relative.flex')]:[];let selected=4;const selectRow=(index:number)=>{selected=(index+rows.length)%rows.length;rows.forEach((row,i)=>{row.setAttribute('aria-selected',String(i===selected));row.style.background=i===selected?'#273747':'';const marker=row.firstElementChild as HTMLElement;if(marker)marker.textContent=i===selected?'❭':'·';});};const pickerKey=(e:KeyboardEvent)=>{if(!rows.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();selectRow(selected+(e.key==='ArrowDown'?1:-1));}if(e.key==='Enter'){e.preventDefault();announce((rows[selected]?.children[1]?.textContent||'Model')+' selected');}if(e.key==='Escape'){e.preventDefault();picker?.blur();}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const row=rows[selected];const effort=row.querySelector<HTMLElement>('[style*="width:7ch"]');if(effort){const values=['Low','Medium','High','Max'];let i=values.indexOf(effort.textContent||'Medium');i=(i+(e.key==='ArrowRight'?1:3))%4;effort.textContent=values[i];}}};picker?.addEventListener('keydown',pickerKey);rows.forEach((row,i)=>{row.style.cursor='pointer';row.setAttribute('role','option');row.onclick=()=>selectRow(i)});
root.querySelectorAll('form input:not([type=checkbox]):not([type=hidden])').forEach(input=>{(input as HTMLInputElement).required=true});
root.addEventListener('click',click);root.addEventListener('submit',submit);root.addEventListener('change',change);return()=>{clearTimeout(timer);picker?.removeEventListener('keydown',pickerKey);root.removeEventListener('click',click);root.removeEventListener('submit',submit);root.removeEventListener('change',change)}},[slug]);
useEffect(()=>{if(!modal)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const previous=document.activeElement as HTMLElement;const dialog=ref.current?.querySelector<HTMLElement>('[role=dialog]');const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal('');if(e.key==='Tab'&&dialog){const items=[...dialog.querySelectorAll<HTMLElement>('button,a[href],input,[tabindex="0"]')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',close);return()=>{document.body.style.overflow=old;previous?.focus();document.removeEventListener('keydown',close)}},[modal]);
return <div ref={ref}>{children}{notice&&<div className="puku-toast" role="status"><Check size={18}/>{notice}</div>}{modal&&<div className="puku-modal-backdrop" onClick={()=>setModal('')}><div className="puku-modal" role="dialog" aria-modal="true" aria-label="PUKU" onClick={e=>e.stopPropagation()}><button className="puku-modal-close" aria-label="Close dialog" onClick={()=>setModal('')} autoFocus><X/></button><img src="/puku-logo.png" width="40" alt="PUKU"/>{modal==='video'?<><h2>Video unavailable</h2><p>This source video was not available in the captured page. You can explore the product previews below.</p><a href="/cloud" className="puku-action">Explore PUKU Cloud <ArrowRight size={16}/></a></>:<p>{modal}</p>}</div></div>}</div>}
