import fs from 'fs';import path from 'path';import postcss from 'postcss';import {load} from 'cheerio';
const base='content/pages';
// Scope the university stylesheet so it cannot change the marketing pages.
let css=fs.readFileSync('public/assets/b6be645da4404e09.css','utf8');css=css.replace(/@import[^;]+;/g,'').replace(/url\([^)]+\)/g,'url(/assets/8f7590be9363096d.woff2)');const tree=postcss.parse(css);tree.walkRules(rule=>{if(rule.parent?.type==='atrule'&&rule.parent.name.includes('keyframes'))return;rule.selectors=rule.selectors.map(s=>'.route-university '+s.replace(/:root|\bhtml\b|\bbody\b/g,':is(.route-university,#app)'));});fs.writeFileSync('public/university.css',tree.toString());
let $=load(fs.readFileSync(base+'/university/page.html','utf8'),null,false);$('.legacy-banner').remove();$('a').each((i,e)=>{const href=$(e).attr('href');if(href?.startsWith('/#/'))$(e).attr('href','/university'+href)});fs.writeFileSync(base+'/university/page.html',$.html());
$=load(fs.readFileSync(base+'/review/page.html','utf8'),null,false);const shell=$('[class]').filter((i,e)=>($(e).attr('class')||'').includes('overflow-y-auto overflow-x-hidden px-6')).first();shell.attr('class','review-content');if(shell.length)fs.writeFileSync(base+'/review/page.html','<div class="review-shell">'+shell.html()+'</div>');
for(const dir of fs.readdirSync(base)){const file=base+'/'+dir+'/page.html';if(!fs.existsSync(file))continue;const $=load(fs.readFileSync(file,'utf8'),null,false);$('img[src*="logo-devin"],img[alt="Devin"],img[alt="PUKU"]').each((i,e)=>{if(/logo|devin/.test($(e).attr('src')||''))$(e).attr('src','/puku-logo.png')});$('button').each((i,e)=>{if($(e).text().includes('curl -fsSL')){$(e).attr('data-installer','true').attr('aria-label','PUKU CLI installer');$(e).find('code').length?$(e).find('code').text('PUKU CLI installer coming soon'):$(e).text('PUKU CLI installer coming soon')}});$('a').each((_,e)=>{let href=$(e).attr('href');if(!href)return;if(href.includes('docs.devin.ai')||href.includes('cli.devin.ai'))$(e).attr('href','/docs');else if(href.includes('app.devin.ai/login'))$(e).attr('href','/login');else if(href.includes('app.devin.ai/signup'))$(e).attr('href','/signup');else if(href.includes('app.devin.ai/review'))$(e).attr('href','/review');else if(href.includes('learn.devinenterprise.com'))$(e).attr('href','/university');else if(href.includes('devin.ai/download'))$(e).attr('href','/download');});fs.writeFileSync(file,$.html());}
const customerFile=base+'/customers/page.html';const customers=load(fs.readFileSync(customerFile,'utf8'),null,false);const usecases={'Testing & QA Automation':/test|quality assurance|regression|coverage/i,'Greenfield Development':/new feature|new product|build|development/i,'Code Maintenance':/maintenan|refactor|technical debt|bug/i,'Documentation':/document/i,'Incident Triage':/incident|triage|on.call/i,'Migrations & Modernizations':/migrat|moderniz/i,'Rapid Prototyping':/prototyp|experiment/i,'Reducing Tech Debt':/tech.*debt|legacy|refactor/i};customers('a[href^="/customers/"]').each((i,e)=>{const slug=customers(e).attr('href').slice(1).replaceAll('/','__');let text=customers(e).text();try{text=load(fs.readFileSync(base+'/'+slug+'/page.html','utf8')).text()}catch{}customers(e).attr('data-usecases',Object.entries(usecases).filter(([name,re])=>re.test(text)).map(([name])=>name).join('|'));});fs.writeFileSync(customerFile,customers.html());


const uncaptured=new Set(JSON.parse(fs.readFileSync('content/external-routes.json','utf8')));for(const dir of fs.readdirSync(base)){const file=base+'/'+dir+'/page.html';if(!fs.existsSync(file))continue;const $=load(fs.readFileSync(file,'utf8'),null,false);$('a[href^="/"]').each((_,e)=>{const href=$(e).attr('href');if(uncaptured.has(href.split(/[?#]/)[0].slice(1)))$(e).attr('href','https://devin.ai'+href)});fs.writeFileSync(file,$.html());}
